### ISSUE TITLE
Masking for N size 10 -20

### ISSUE THREAD

**Issue by jeanho1** [nm-ped-accountability/SBA-Science-2018-2019#1]
# N = 10-20
        else {
            if (level == "Level1" | level == "Level2") {
                row$pct <- row[["Level1"]] + row[["Level2"]]
            }
            else {
                row$pct <- row[["Level3"]] + row[["Level4"]]
            }
            row$merge <- 1
        }
        masked <- rbind(row, masked)    
    }
    masked <- masked[order(masked$SORT, 
                           masked$SORTCODE, 
                           masked$schnumb, 
masked$Grade), ]

ADD GE 80 and LE 20 to N size 10 -20 masking.

**Comment by yaoyunhz** [comment]
@jeanho1 Thanks Jeanho. I've fixed this issue. Please let me know if you notice any other issues.


# N = 10-20
        else {
            if (level == "Level1" | level == "Level2") {
                row$pct <- row[["Level1"]] + row[["Level2"]]
            }
            else {
                row$pct <- row[["Level3"]] + row[["Level4"]]
            }
            row$merge <- 1
            row$pct1 <- row$pct
            row$pct[row$pct1 < 21] <- "LE 20"
            row$pct[row$pct1 >= 21 & row$pct1 < 30] <- "21-29"
            row$pct[row$pct1 >= 30 & row$pct1 < 40] <- "30-39"
            row$pct[row$pct1 >= 40 & row$pct1 < 50] <- "40-49"
            row$pct[row$pct1 >= 50 & row$pct1 < 60] <- "50-59"
            row$pct[row$pct1 >= 60 & row$pct1 < 70] <- "60-69"
            row$pct[row$pct1 >= 70 & row$pct1 < 80] <- "70-79"
            row$pct[row$pct1 >= 80] <- "GE 80"
            row$pct1 <- NULL
}
